<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Today extends Model
{
    use HasFactory;
    protected $fillable = [
            'user_id',
            'work_office',
            'work_soho',
            'work_3pl',
            'life',
            'move',
            'office_area',
            'office_person',
            'three_pl_type',
            'three_pl_city',
            'green_power',
            'light_time_office',
            'light_led_office',
            'light_time_soho',
            'light_led_soho',
            'light_time_3pl',
            'light_led_3pl',
            'ac_time_office',
            'ac_time_soho',
            'ac_time_3pl',
            'printed_paper',
            'pc_time',
            'drink_cup_type',
            'move_floor_number',
            'move_walk',
            'move_out_number',
            'move_out_departure1',
            'move_out_arrival1',
            'move_out_type1',
            'move_out_distance1',
            'move_out_departure2',
            'move_out_arrival2',
            'move_out_type2',
            'move_out_distance2',
            'move_out_departure3',
            'move_out_arrival3',
            'move_out_type3',
            'move_out_distance3',
            'move_out_departure4',
            'move_out_arrival4',
            'move_out_type4',
            'move_out_distance4',
            'breakfast_image',
            'breakfast_place',
            'breakfast_type',
            'breakfast_volumn',
            'breakfast_vegetable_volumn',
            'breakfast_vegetable_type',
            'breakfast_vegetable_produced',
            'breakfast_main_volumn',
            'breakfast_main_type',
            'breakfast_main_produced',
            'lunch_image',
            'lunch_place',
            'lunch_type',
            'lunch_volumn',
            'lunch_vegetable_volumn',
            'lunch_vegetable_type',
            'lunch_vegetable_produced',
            'lunch_main_volumn',
            'lunch_main_type',
            'lunch_main_produced',
            'dinner_image',
            'dinner_place',
            'dinner_type',
            'dinner_volumn',
            'dinner_vegetable_volumn',
            'dinner_vegetable_type',
            'dinner_vegetable_produced',
            'dinner_main_volumn',
            'dinner_main_type',
            'dinner_main_produced',
            'sports_time',
            'sports_type',
            'sports_place',
            'rest_time',
            'rest_type',
            'activity_date',
            'shopping_ce',
            'shopping_cloth',
            'shopping_ce',
            'shopping_hobby',
            'shopping_office',
            'shopping_daily',
            'shopping_tabacco',
            'shopping_other',
            'works_carbon',
            'move_carbon',
            'life_carbon',
            'foods_carbon',
    ];

    public function user() {
        return $this->belongsTo(User::class, 'user_id');
    }
}
